# docker-compose.yaml
version: '3.3'
services:

  elasticsearch:
    build:
      context: "./es"
      dockerfile: "Dockerfile"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true
    environment:
      discovery.type: single-node
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    restart: always

  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    ports:
      - 8002:8002
    volumes:
      - backend-data:/src
    depends_on:
      - elasticsearch
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    ports:
      - 8501:8501
    volumes:
      - frontend-data:/src

volumes:
  es-data:
    driver: local
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/api
  frontend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend/app
    